project:
  type: website
  output-dir: docs

website:
  title: "Thiago VedoVatto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/thiagovedovatto
format:
  html:
    theme: default
    css: styles.css

editor: source