project:
  type: website
  output-dir: docs

website:
  title: "Thiago VedoVatto"
  site-url: "https://thiagovedovatto.github.io/"
  navbar:
    right:
      - text: "Sobre"
        href: about.qmd
    page-footer:
    center: 
      - text: "Sobre"
        href: about.qmd

format:
  html:
    theme: default
    css: styles.css

editor: source